### ISSUE TITLE
circular json is returned in the event of an error

### ISSUE THREAD

**Issue by pasupulaphani** [chris-l/generator-restify#3]
It is a typical error when you try to stringify a json circular reference.

Error happens with in "formatters".

**Comment by chris-l** [comment]
Yes, but that is not an error of the generator itself.

You need to check your function that the object you are sending don't have circular references.

If the problem is indeed on the object you are sending, if you want, you can hide the error by using a replacer function on the call of stringify. Here is a function to do that: http://stackoverflow.com/a/11616993/2507726 
Use that function here: https://github.com/chris-l/generator-restify/blob/master/app/templates/_index.js#L35

I'm not including that function on the generator because that would only hide the problem.

**Comment by pasupulaphani** [comment]
Hi @chris-l , I'm not throwing any error object. it just happens to any unhand led error thrown.

**Comment by chris-l** [comment]
Ohh, I see! The right thing is to handle the error, perhaps with a`try/catch` block.

However, I agree that only returning an circular reference error is just wrong. So I added a default handler here: @d5bc97e

Let me know if that stops returning that circular reference error for you.
